Update tload

diff --git a/tload b/tload
--- a/tload
+++ b/tload
@@ -11,7 +11,9 @@ CU=$(./.setupcheck curl)
 RS=$(./.setupcheck rsync)
 EX=$(./.setupcheck expect)
 if [ "$OS" == "0" ] || [ "$SP" == "0" ] || [ "$CU" == "0" ] || [ "$RS" == "0" ] || [ "$EX" == "0" ]; then
-echo "Requirements have not been installed. Please wait while they are being installed. "
+clear
+echo "Welcome to T-Load. This must be your first use or the required files must have been deleted. So please wait untill all the required files have been setup. "
+sleep 5
 #Setup
 pkg install openssh -y
 pkg install sshpass -y
@@ -56,6 +58,62 @@ touch $HOME/.msf_default/exploit
 ln -s $HOME/T-Load/tload /data/data/com.termux/files/usr/bin/tload
 chmod +x /data/data/com.termux/files/usr/bin/tload
 #End Setup
+fi
+no=$(ls $HOME/.msf_default | wc -l)
+if [ ! -d $HOME/.msf_default ] || if [ "$no" != "7" ];
+then
+{
+ echo " Welcome to T-Load. This must be your first use or the required files must have been deleted. So please wait untill all the required files have been setup. "
+ sleep 4
+ clear
+ echo "Setting up things for you. Please wait."
+ sleep 3
+ #Setup
+ clear
+ pkg install openssh -y
+pkg install sshpass -y
+pkg install curl -y
+pkg install rsync -y
+apt-get install expect -y
+[[ -s $HOME/.msf_default/msfload ]]
+msfl=$(echo $?)
+mkdir $HOME/.msf_default
+if [ $msfl = "1" ]
+then
+echo '#!/data/data/com.termux/files/usr/bin/expect -f
+source /data/data/com.termux/files/home/.msf_default/port
+source /data/data/com.termux/files/home/.msf_default/host
+source /data/data/com.termux/files/home/.msf_default/exploit
+source /data/data/com.termux/files/home/.msf_default/payload
+spawn msfconsole
+expect "msf > "
+send "use $exploit \r"
+expect "msf exploit(handler) > "
+send "set payload $payload \r"
+expect "msf exploit(handler) > "
+send "set lhost $lhostused \r"
+expect "msf exploit(handler) > "
+send " set lport $lportused \r"
+expect "msf exploit(handler) > "
+send "exploit \r"
+interact' >> $HOME/.msf_default/msfload
+fi
+cd $HOME/T-Load
+chmod +x $HOME/.msf_default/msfload
+chmod +x embed
+chmod +x updates
+chmod 600 key
+chmod +x redownload
+touch $HOME/.msf_default/pay
+touch $HOME/.msf_default/port
+touch $HOME/.msf_default/port
+touch $HOME/.msf_default/host
+touch $HOME/.msf_default/payload
+touch $HOME/.msf_default/exploit
+ln -s $HOME/T-Load/tload /data/data/com.termux/files/usr/bin/tload
+chmod +x /data/data/com.termux/files/usr/bin/tload
+#End Setup
+}
 fi
 ## End Auto Setup
 #### UPdater
